import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import ReactPlayer from "react-player";

import useWindowDimensions from "../hooks/useWindowDimensions";
import styles from "../styles/Home.module.css";

const Home = () => {
  const { width, height } = useWindowDimensions();
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  const vidContWidth = width > 600 ? width / 2 - width * 0.1 : 0.9 * width;

  return (
    <div className={styles.container}>
      <Head>
        <title>Inkstory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/icons/logo.svg" // Route of the image file
          height={100} // Desired size with correct aspect ratio
          width={300} // Desired size with correct aspect ratio
          alt="Beekle"
        />

        <p className={styles.description}></p>

        <div className={styles.vidContainer}>
          {domLoaded && (
            <ReactPlayer
              url="https://inkstory.s3.ap-south-1.amazonaws.com/Videos/psy_vid1.mp4"
              width={vidContWidth}
              height={vidContWidth}
              controls
            />
          )}
          <iframe style={{ height: vidContWidth, width: vidContWidth }} src='/psm1.pdf' />
        </div>

        <div className={styles.vidContainer} style={{ flexDirection: width > 600 ? 'row-reverse' : 'column'}}>
          {domLoaded && (
            <ReactPlayer
              url="https://inkstory.s3.ap-south-1.amazonaws.com/Videos/pom_part2.mp4"
              width={vidContWidth}
              height={vidContWidth}
              controls
            />
          )}
          <iframe style={{ height: vidContWidth, width: vidContWidth }} src='/psm2.pdf' />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
